# Generated by Django 4.0.6 on 2022-07-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('issuetype', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
